
import javax.swing.JOptionPane;

/**
 *
 * @author TanzidKhan
 */
public class GShape extends javax.swing.JFrame {

    /**
     * Creates new form GShape
     */
    public GShape() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GS = new javax.swing.JLabel();
        Shape = new javax.swing.JComboBox();
        OK = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G-Shape Calculator");
        setBackground(new java.awt.Color(255, 255, 153));
        setForeground(new java.awt.Color(240, 240, 240));
        setMinimumSize(new java.awt.Dimension(1050, 656));
        setName("MFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1050, 656));
        setResizable(false);
        getContentPane().setLayout(null);

        GS.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        GS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gsha.png"))); // NOI18N
        GS.setToolTipText("");
        getContentPane().add(GS);
        GS.setBounds(150, 100, 197, 50);

        Shape.setBackground(new java.awt.Color(0, 51, 0));
        Shape.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        Shape.setForeground(new java.awt.Color(255, 0, 0));
        Shape.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Circle", "Cone", "Cube", "Cuboid", "Cylinder", "Parallelogram", "Polygon", "Sphere", "Triangle" }));
        Shape.setToolTipText("Select a Shape");
        Shape.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 4, true));
        Shape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShapeActionPerformed(evt);
            }
        });
        getContentPane().add(Shape);
        Shape.setBounds(565, 139, 170, 36);

        OK.setBackground(new java.awt.Color(255, 102, 102));
        OK.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        OK.setForeground(new java.awt.Color(204, 0, 0));
        OK.setText("DONE");
        OK.setToolTipText("Click this after You have choosen your Shape");
        OK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(768, 140, 86, 36);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_CSE.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(20, 20, 140, 140);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select a Shape:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 110, 110, 20);

        backG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/love it.jpg"))); // NOI18N
        backG.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(backG);
        backG.setBounds(0, 0, 1050, 656);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShapeActionPerformed
    
    }//GEN-LAST:event_ShapeActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        GObject G1=new GObject();
        dispose();
       G1.setS(Shape.getSelectedItem().toString());
      
        if ((G1.getS()=="Cube")||(G1.getS()=="Cuboid")){
           MFrame1 M =new MFrame1();
           M.setVisible(true);
        }
        else if ((G1.getS()=="Cone")||(G1.getS()=="Cylinder")){
            RFrame2 R1=new RFrame2();
            R1.setVisible(true);
        }
        else if ((G1.getS()=="")||(G1.getS()=="Cylinder")){
            RFrame2 R1=new RFrame2();
            R1.setVisible(true);
        }
        else if (G1.getS()=="Parallelogram"){
            RFrame3 R3=new RFrame3();
            R3.setVisible(true);
        }
        else if (G1.getS()=="Polygon"){
            RFrame4 R4=new RFrame4();
            R4.setVisible(true);
        }
        else if(G1.getS()=="Triangle"){
            MFrame5 R5=new MFrame5();
            R5.setVisible(true);
        }
        else if ((G1.getS()=="Sphere")||(G1.getS()=="Circle")){
            RFrame6 R6=new RFrame6();
            R6.setVisible(true);
        }
        
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GShape().setVisible(true);
               
            }
        });
       
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel GS;
    private javax.swing.JButton OK;
    public static javax.swing.JComboBox Shape;
    private javax.swing.JLabel backG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables


}

