
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TanzidKhan
 */
public class MFrame1 extends javax.swing.JFrame  {

    /**
     * Creates new form MFrame1
     */
    public MFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Mujib = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G-Shape Calculator");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setToolTipText("Enter the Length");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 160, 250, 40);

        jTextField2.setToolTipText("Enter the breadth");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 240, 250, 40);

        jTextField3.setToolTipText("Enter the Height");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 320, 250, 40);

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel4.setText("Enter Height");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 320, 100, 30);

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel3.setText("Enter Breadth");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 250, 100, 30);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel2.setText("Enter Length");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 170, 100, 30);

        jButton1.setBackground(new java.awt.Color(231, 215, 124));
        jButton1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.setToolTipText("Press to get Result");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 58, 26), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 440, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_java_new.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("G-Shape");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 100, 80);

        jButton2.setBackground(new java.awt.Color(231, 215, 124));
        jButton2.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setToolTipText("Return to main window");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 58, 26), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 503, 100, 30);

        Mujib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkoto.png"))); // NOI18N
        getContentPane().add(Mujib);
        Mujib.setBounds(0, -40, 920, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GObject cb=new GObject();
        Cube C=new Cube();
        Cuboid Cc=new Cuboid();
        RFrame RF=new RFrame();
       
        cb.setL(Double.parseDouble(jTextField1.getText()));
        cb.setB(Double.parseDouble(jTextField2.getText()));
        cb.setH(Double.parseDouble(jTextField3.getText()));
        dispose();
       
        if(GShape.Shape.getSelectedItem().toString()=="Cube"){
           RF.setVisible(true);
           RF.area.setText((C.Area(cb.getL())));
           RF.perimeter.setText((C.Peri(cb.getL()))); 
           RF.diagonal.setText((C.Diag(cb.getL())));
           RF.volume.setText((C.Vol(cb.getL())));
        }
        else if(GShape.Shape.getSelectedItem().toString()=="Cuboid"){
           RF.setVisible(true);
           RF.area.setText((Cc.Area(cb.getL(),cb.getB(),cb.getH())));
           RF.perimeter.setText((Cc.Diag(cb.getL(), cb.getB(),cb.getH())));
           RF.diagonal.setText((Cc.Diag(cb.getL(),cb.getB(),cb.getH())));
           RF.volume.setText((Cc.Vol(cb.getL(),cb.getB(),cb.getH())));
        }
        //Start next Condition -TANZID
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GShape G=new GShape();
        dispose();
        G.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mujib;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
