/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TanzidKhan
 */
public class RFrame extends javax.swing.JFrame {

    /**
     * Creates new form RFrame
     */
    public RFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area = new javax.swing.JTextField();
        diagonal = new javax.swing.JTextField();
        perimeter = new javax.swing.JTextField();
        volume = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G-Shape Calculator");
        setMinimumSize(new java.awt.Dimension(904, 604));
        setResizable(false);
        getContentPane().setLayout(null);

        area.setBackground(new java.awt.Color(204, 204, 0));
        area.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        area.setForeground(new java.awt.Color(255, 0, 0));
        area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 5, true));
        getContentPane().add(area);
        area.setBounds(200, 200, 140, 40);

        diagonal.setBackground(new java.awt.Color(204, 204, 0));
        diagonal.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        diagonal.setForeground(new java.awt.Color(255, 0, 0));
        diagonal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 5, true));
        getContentPane().add(diagonal);
        diagonal.setBounds(370, 310, 140, 40);

        perimeter.setBackground(new java.awt.Color(204, 204, 0));
        perimeter.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        perimeter.setForeground(new java.awt.Color(255, 0, 0));
        perimeter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 5, true));
        getContentPane().add(perimeter);
        perimeter.setBounds(20, 310, 140, 40);

        volume.setBackground(new java.awt.Color(204, 204, 0));
        volume.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        volume.setForeground(new java.awt.Color(255, 0, 0));
        volume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 5, true));
        getContentPane().add(volume);
        volume.setBounds(200, 450, 140, 40);

        jLabel2.setBackground(new java.awt.Color(0, 51, 0));
        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("          AREA");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 4, true));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 170, 140, 30);

        jLabel3.setBackground(new java.awt.Color(0, 51, 0));
        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("     PERIMETER");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 4, true));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 280, 140, 30);

        jLabel4.setBackground(new java.awt.Color(0, 51, 0));
        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("        VOLUME");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 4, true));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 420, 140, 30);

        jLabel5.setBackground(new java.awt.Color(0, 51, 0));
        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("       DIAGONAL");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 4, true));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 280, 140, 30);

        Exit.setBackground(new java.awt.Color(204, 0, 0));
        Exit.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 0));
        Exit.setText("EXIT");
        Exit.setToolTipText("Thank You For Supporting Us ! ");
        Exit.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 5)));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(730, 490, 130, 40);

        c1.setBackground(new java.awt.Color(204, 0, 0));
        c1.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 0));
        c1.setText("CONTINUE");
        c1.setToolTipText("Return to the Starting Window");
        c1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 5)));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(200, 310, 130, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_java_new.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 20, 120, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5272619025_437356c7db.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 910, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        dispose(); 
        GShape G2=new GShape();
         G2.setVisible(true);
    }//GEN-LAST:event_c1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    public static javax.swing.JTextField area;
    private javax.swing.JButton c1;
    public static javax.swing.JTextField diagonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField perimeter;
    public static javax.swing.JTextField volume;
    // End of variables declaration//GEN-END:variables
}
